server:
  address: localhost
  port: 8088

# data base configuration

# Redis Config
spring:
#  cache:
#      redis
#  redis:
#     host:localhost
#     port:6379
  profiles:
    active: "default"
  application:
    name: bdx-api
  mvc:
    dispatch-options-request: true  
  jpa:
     hibernate:
#         naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 
  http:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
     
#  data:
#      mongodb:
##        authentication-database : admin
##        username : root
##        password : root  
#        database : xmltemplates
#        port : 27017
#        host : 192.168.1.113 
 
eureka:
  client:
    serviceUrl:
       defaultZone: ${EUREKA_URI:http://192.168.1.112:8761/eureka}
    healthcheck:
      enabled: true
    lease:
      duration: 5  
    instance:
      prefer-ip-address: true
      ip-address: ${server.address}
      instance-id: ${server.address}:${server.port}
                   
CORS:
  allowedOrigin: http://10.199.0.100:9090
  
endpoints:
    health:
       sensitive : false

management:
    security:
        enabled: false

owit:
  common:
    downloadFileDir: "C:\\bordereauapp\\"
    configFile: "C:\\properties\\"
    fileDirPlan : "C:\\bordereauapp\\plans\\"
    fileDirDownloads : "C:\\bordereauapp\\Downloads\\"
    fileDirReport : "C:\\bordereauapp\\Report\\"
    reportURL : "https://dev-rpt.oneworldinstech.com/rs/Pages/ReportViewer.aspx"
    reportServerUserName : "bdx-rs"
    reportServerPassword : "Owit123!!"
    validateCollection : "validateXMLData"
    lookupServiceId : "LOOKUPDATAMANGEMENT"
    planServer: https://dev-poc.owitglobal.com/bdx-api/
    bdxReq: "C:\\inetpub\\wwwroot\\OWITServices\\BordereauRulesEditor\\xml\\bdx-req"
    bdxRules: "C:\\inetpub\\wwwroot\\OWITServices\\BordereauRulesEditor\\xml\\bdx-rules"

  keycloak:
    baseURL: "http://localhost:8080/auth/"
    
